url: https://www.codamono.com
baseurl: 

# Site settings
title: CODAMONO
email: kim@codamono.com
description: "Codamono is all about software development and web services. There are no limits, but Codamono specializes in biomedical applications, genomic data-processing, and web-services."

# Color settings (hex-codes without the leading hash-tag)
color:
  codamono-text: d6d6d6
  primary: fed136
  secondary: fec503  
  info-primary: 4cb1dc
  info-secondary: 3999c3  
  secondary-dark: 333
  navbar-dark: 292929

# Team names, titles and social links
people:
- name: Joachim Baran
  pic: 1
  position: Ph.D., CAPM<br />Sole Proprietor
  social:
    - title: twitter
      url: https://twitter.com/indiedotkim
    - title: linkedin
      url: https://www.linkedin.com/profile/view?id=AAIAAAmScH0B38m_GBr0vlUmdTX7Ueed6PSit7I
    - title: pencil
      url: http://indie.kim/

#- name: Larry Parker
#  pic: 2
#  position: Lead Marketer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #

#- name: Diana Petersen
#  pic: 3
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CODAMONO
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 5-121 Marion Street
  - line: Toronto, Ontario
  - line: M6R 1E6
  - line: Canada

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
    syntax_highlighter: rouge
